[package]
edition = "2021"
name = "homescreen_default"
version = "0.0.1-dev"

[lib]
crate-type = ["cdylib"]

[dependencies]
hmny_common = {path = "../../crates/common", default-features = false, features = ["homescreen"]}
