[package]
edition = "2021"
name = "hmny_macros"
version = "0.0.1-dev"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0"
quote = "1.0.32"
syn = {version = "2.0.28", features = ["full"]}
